### ISSUE TITLE
Equation 3 might be incorrect?

### ISSUE THREAD

**Issue by yshen47** [jiaxinxie97/HFGI3D#2]
I am a bit confused on equation 3 in the arxiv paper. The diffference map D seems to be on pose p_0. However, it is doted with G(z, p_i) in equation 3. How to dot 2d map and image from different pose? Is there any projection step on D in the process? thanks!

**Comment by jiaxinxie97** [comment]
Hi, 
Yes, you are right. The p_i in equation 3 is a typo, there should be p_o. The equation 4 should be p_i. We will correct it soon

**Comment by yshen47** [comment]
gotcha, thanks for the fast response! And another question is how you get z_e at the first place? is that by directly optimizing on x_0 in initial pose to do the GAN inversion task?

**Comment by jiaxinxie97** [comment]
Yes, z_e is optimized from random sampled latent code by backwards loss between generated image and x0, the pose is the input view(x0) pose.

**Comment by yshen47** [comment]
I see that makes sense to me now, thank you!
